# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

def countNucleotides(DNAstrand):
    Nucleotides = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuc in DNAstrand:
        Nucleotides[nuc] += 1
    return Nucleotides


DNAStrand = "ACACAGATCCTGGGCGACTCAAGTACCTGCGCGGTGCGAGGACTTGTGTGTAGCTCCCGGTAGGGGAGAGGAGCCTGACGCACAGTTGATAACTTCCAGAGGGGTGGTTCCGTCATGTGTTGCGGTGCTAGAACGTGGCTTAGCGGCCCTCGAAGGCATGGCACGAGGCCTACTACGCGCAGGACTGGTCGGACGGATCCCCTGGATGTGTGGTCTGCAGGGTATACTGAAGAGGTCTTACCGGCGCAAACTGAAGCTTCGCGATCAGCCGTCTTCCTCACTGCCCCTACTGTTATATAACTTTTCTGTTTCAAAAGACTAAGTTAATCGCGTTTAAGTCAAACAAGCATGCTAGTACCAAAATGGGGACTAGCGTCCGGACCGTTCAAGGTAAAGCATGAGCAAGTAATCGACGAGTAGTTTCCCTAAACGGCCGATCCTAGGTCGGCTTGCCATCCCGCCCTTCCTAGCATAGCGTGTACGAGAGTGTAATGCTAAGAGATCTAAGGACACAGGCCCCACCTCCCCACAGGCTCGAGACCCGTGTCTACCGTCGCTGATCGCCCATGGTGGGGATGGCGGTACCTATAGCTAGCCTTGCGATATATTTAGGCCAGGATCATAGAGCCGTCGGGGCATAAGTTGAATCCCTTGGCTAATTCAGGTAGGTGTGCGGGAGAGAGAGGACCTGGCTAGTGTCCATTAGTGAGTTACGTGCAGTTTATTATCAGCCAAAAATACGCGTATGTCATGCTCTTGATGGCCCCTACGACAGATCAATTCGTACTGCGGACGAAATAGTTAGGACCGAGGCTGTTTAAGAGCTTGAGTGGCATAACAAGGCTTGCTCACGCCGCAAGCTATTTTTTTCTCGGTCTTCGTGAGCACCCACCTGGCCGTGCGTCCGTTCGGGAAACTAAGGATGAATCGGGCCCAGGTTGACCACGAAAATAGGTACTCAGAGAC"
result = countNucleotides(DNAStrand)

print(' '.join([str(val) for key, val in result.items()]))