# -*- coding: utf-8 -*-
"""
Created on Mon Nov  9 14:49:19 2020

@author: walsh
"""

from Bio.SeqUtils import GC






a = GC("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG")
b = GC("CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC")
c = GC("CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT")


seqDict = {a: 'Rosalind_6404', b: 'Rosalind_5959', c: 'Rosalind_0808'}


list = [a, b, c]
x = (max(list))
print(x)
print(seqDict.get(x))
