# -*- coding: utf-8 -*-
"""
Created on Sun Oct 25 11:54:35 2020

@author: walsh
"""

def hammingDist(seq1, seq2):
    pointMut = 0
    x = len(seq1)
    for nuc in range (x):
        if seq1[nuc] != seq2[nuc]:
            pointMut += 1
    return(pointMut)
    
        
        
        
        
        
        
        
        
result = hammingDist("TGGGCGTGAAAAAGCTGGAAGGCTAAAATTTTCAACACATTCAGAACTTGAACTGGTGATCAAATCGCCCAGCACGGTGCAAAATGGCCTATTGCGAAACGCGCGAAGAGAGCCCAAAACCGTTTGGACACTGTAATGATCACTTTTCGCACTGATGTGAAAGATCGCGACGATGATGCTCCCTAATTATCCTATTGGCACCTTCGATGTCATGCTGATCTTTCACAGATTTTTTATGACCGGTGTTGACTCCCATCCGGCCGCTTCGTGTGAATGTCGAAATGGGACCTAGCATAAGCATTCCTAATTTCCCATCGACGACATATATCGAGAATCCAACCCCACCACACAACCACACTGGCCTCTTCGGGCTGAGTTCATTGCTAGCCTAATTCGAAGCCCTAAAGTCGTGCTACTAGCACCTGGGTATGCATTTTAAAAGAAGATGCCTAGGTGATTGTAGAGTTGTCAGGTGTTAGCTTCGACGCCAACGCCTCTAATTTTATGGTGTGGAAGTCAACGGAACCGAGCCGGGGTGTGGAACATCCGTGTCAGCATGATTGTCTGATTTACTCAGTCTACCAGTGCTAAGTAATAGAATAGTATGCGTAGCGATAAATGTACTGGAAAATGACAGTCGATGTATTCAGAAGCATAAGTACCTATGAATGCCAGTAATTTAGTCTATTAAATACTTTGTAGACGTCAGCCCCGTTCGAATTCCGTCTGGTCCTGAGTTTGGTGCGGTGTTGGTTCAATATGATACGGATAGAAGCAGTTAATGCCGAACTGTTAGCACTATTTCCAGGATGTGGACGGCACCACATAGCCACCCACGAGATCGGGCGTGCGGCATGAAGGTCACATAATGCATAATGGATGTTCCGATAAGCCTGATTATGTACTAAGGGTCTCATCTGAATACCCGCCCTATGACTCCAGAGATGACCTCTTAG", "TAATGATGCAAACGAACGGACTATAACATTAGCCACGTACGATGAACTCTTAGTGGAGGTCGAGCGCCTCACGAGGCGGTACGCTGGTCCTCTTCGATAATCGTGCAGAGACCCGATCATGTGCAAGCCACCCTGGGTGTGGCTCATTACTATGGTGTGAAAGATCGCTACGAAGATCCTTTACAAAGATGATATATAAACTGCACATGACCGGAATGCCATTCACAGATTGTTAATGCCCGATCTACACTCCTATCCGCCCTATTCGTGTGAGTGTGGTAGCCAGGAATACCACAAGCAGTTCAAAAAGCACGGCTACTAAATATCGCCTTGAACAAGTATCCAATTACAACCAGTCTAAGCATTCTGGAATTAAATCATTGAAATACATATTTGAGTTATCCAAGACACCCAAGCGGCACCTCAGAGTGTCTTTTCTTTCCGGGGGCCGAGTCGCTTGTATAAGATTTAACACTTATCAGCGTAACGGAATCGTCTCCTTGGATCGTGGGGCAGTGCTTGGCCACGACCCTCGCTGCGGACTATCCGGATCTGGGCAGGTGACGGCTCGATCATAAGGGCCAAGACTCAATAACATAATAGTTTGTGTGTTAATTAATTTGGAGAAACGTTGCAGTTGATCGTTTTATCGACAAAAGACAGTATCAAGTGCTGAGAGTTAGGATATTTAGCGCTTCGAAGCCTAGCGCCCCGTGAGGATTAAATCGTACCCAGGGTCTGATTCGTAAGTGCCGCCTTATCTACCATTCGGTCGCCTATAGCGCTACAATGATAGTGCAATCCGAGGCCTGTTCAAGGCACAAATTTGACAGACCGCTGATCTGGTGCGATCCATGAGGATCACAGAAGGAACCAGTGAATTCCTGACGGTTACTAGAGTGTAAGAGTAGGCACACTGAACACGTCACACTCAGAAGACAATGAAGATGTTTATC")
print(result)
    