# -*- coding: utf-8 -*-
"""
Created on Thu Oct 29 21:23:11 2020

@author: walsh
"""

def reverseComplement(DNAstrand):
    x = {"A":"T", "T":"A", "C":"G", "G":"C"}
    return''.join([x[nuc] for nuc in DNAstrand])[::-1]


print(reverseComplement("ACATCACTGTGGTTCAGGGAGGCTACTCATTCAGCAAAGGTCGTACGAGTTTACCCTTATGACAAGACCCGTGAGATTATTGGTAACGAGTCAATCGGCGACTGGTTACGATCACTAAAGTTACCAAATAAGCTTTAGTCGAACGCCAGCGATCACTCACGACATTGGCCGATTTTGTCCAAAGGCTAGTAAGATGAGTAAAGCATGCGTGAACACTGGGGTATTAACTCGTCCCCCCTCTGTTTGATCTATAAGTAATGACTCAGGGCCTGCAGTAGCAATTTAGGCAAGTTATGGCGCCTGCGATCGAAATGTGCAACCCCGCCCAAGGAGAATTACCAAGTCATTTGAGCACGAACGTCGATCCGCAATTGGGCTCTCTGAATCACGGCGGTCTAGCTGCTACATCAGGTATTAAAACTATTTGCTTGCAACAGGTCGGAACATGAAGAAGGCGGTCGAGGCACACGGTTTCTCCTCACTCGCTGTTATGAAGATCCACATCGCTCTCCGATACATTTCTACATATGCAACCTAATGGTGTGTCTACTCTATGTTGGATTATTGGAGACACCGATTAGAGCCGCATTGGGGAGGCAGAAGATAGCGCCTTCGTTCGATCATATAACAGATCCGTGCTCCATAGAGCTTGTGCAGATTTGGACCCCTTGTCTCAATCCAAAGAGTATCGGCTCTCGCAGCCTAGACGCCAATCCTGCCCCTTAAAATGAAAACCCGTACATAAAGCCATTGAATTTAACTAGCGACAAGACCGCAGCGCGCTGCGTAAATTTTTACGGCGAGTCAGATATATGTATCACATGTTCATAGCAGCCGTCGCTACAGCGATATTCACCACTTACAGGAGCTTATGGTCGCATGCTGGACAAGGTTACTCCTCACATGGAGCATCGGAGTCGGCGAGAGATCCGTCTCT"))